# Generated by Django 5.2.8 on 2025-12-01 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_symptom_remove_triageassessment_assessed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagesession',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='symptom',
            name='body_part',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('pain', 'Pain'), ('fever', 'Fever/Infection'), ('respiratory', 'Respiratory'), ('digestive', 'Digestive'), ('neurological', 'Neurological'), ('skin', 'Skin'), ('mental', 'Mental Health'), ('cardiac', 'Cardiac')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='symptom',
            name='severity_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='session_type',
            field=models.CharField(choices=[('form', 'Form-based'), ('chat', 'Chat-based')], default='form', max_length=20),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='symptom_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='disease',
            name='common_symptoms',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='triage.symptom'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='specialty',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='predicted_specialty',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.CreateModel(
            name='SymptomChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='triagesession',
            name='selected_symptoms',
            field=models.ManyToManyField(blank=True, to='triage.symptomchoice'),
        ),
    ]
