# Generated by Django 5.2.8 on 2025-12-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_remove_triagesession_symptoms_symptom_body_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesession',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='triage_sessions', to='triage.symptom'),
        ),
    ]
