# Generated by Django 5.2.8 on 2025-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_videocall'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='caller_peer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videocall',
            name='receiver_peer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
