# Generated by Django 5.2.8 on 2025-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_videocall_caller_peer_id_videocall_receiver_peer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='caller_ice_candidates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocall',
            name='caller_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocall',
            name='receiver_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocall',
            name='receiver_ice_candidates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
