# Generated by Django 6.0.1 on 2026-04-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_videocall_caller_ice_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocall',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
