# Generated by Django 6.0.4 on 2026-04-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_videocall_vonage_session_id'),
        ('messaging', '0005_videocall_recording_enabled_videocall_recording_url'),
    ]

    operations = [
    ]
