# Generated by Django 5.2.8 on 2025-12-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('powder', 'Powder')], default='tablet', max_length=20)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('painkiller', 'Painkiller/Analgesic'), ('antiinflammatory', 'Anti-inflammatory'), ('antiviral', 'Antiviral'), ('antifungal', 'Antifungal'), ('antihistamine', 'Antihistamine'), ('antidepressant', 'Antidepressant'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('vitamin', 'Vitamin/Supplement'), ('hormone', 'Hormone'), ('sedative', 'Sedative/Sleep Aid'), ('other', 'Other')], default='other', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 10ml', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled substance')),
                ('common_side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('diagnosis', models.TextField(help_text='Patient diagnosis/condition')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for patient or pharmacist')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('dispensed', 'Dispensed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateField(help_text='Prescription validity date')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('signed', 'Signed by Doctor'), ('sent', 'Sent to Patient'), ('viewed', 'Viewed by Patient'), ('verified', 'Verified'), ('dispensed', 'Dispensed by Pharmacy'), ('refilled', 'Refilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name_plural': 'Prescription histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 5ml, 2 puffs', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('three_times_daily', 'Three times daily'), ('four_times_daily', 'Four times daily'), ('every_4_hours', 'Every 4 hours'), ('every_6_hours', 'Every 6 hours'), ('every_8_hours', 'Every 8 hours'), ('every_12_hours', 'Every 12 hours'), ('as_needed', 'As needed (PRN)'), ('once_weekly', 'Once weekly'), ('at_bedtime', 'At bedtime'), ('with_meals', 'With meals'), ('before_meals', 'Before meals'), ('after_meals', 'After meals')], max_length=20)),
                ('duration_value', models.PositiveIntegerField(help_text='Duration number')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity to dispense')),
                ('special_instructions', models.TextField(blank=True, help_text='e.g., Take with food, Avoid sunlight')),
                ('refills_allowed', models.PositiveIntegerField(default=0, help_text='Number of refills allowed')),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('allow_generic', models.BooleanField(default=True, help_text='Allow generic substitution')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
