# Generated by Django 6.0.4 on 2026-04-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
